import fetch from 'isomorphic-unfetch'
import Profile from '../../components/Profile'
import Repositories from '../../components/Repositories'
import css from 'styled-jsx/css'

const name = ({user, repos}) => {
    return (
        <div className="user-contents-wrapper">
            <Profile user={user}/>
            <Repositories 
                repos={repos}
                user={user}
            />
            <style jsx>{style}</style>
        </div>
    )
}

// getServerSideProps : 페이지의 데이터를 서버로부터 제공받는 기능을 제공.
export const getServerSideProps = async ({query}) => {
    const {name, page} = query
    try {
        const userRes = await fetch(`https://api.github.com/users/${name}`)
        if(userRes.status === 200) {
             user = await userRes.json()
        }
        const repoRes = await fetch(`https://api.github.com/users/${name}/repos?sort=updated&page=${page}&per_page=10`)
        if(repoRes.status === 200) {
             repos = await repoRes.json()
        }
        return {props: {user, repos}}
    } catch(e) {
        console.log(e)
        return {props: {user, repos}}
    }
}

const style = css`
    .user-contents-wrapper {display: flex; padding: 20px;}
`
let user = {
    login: 'rews7895',
    id: 37057277,
    node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
    avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/rews7895',
    html_url: 'https://github.com/rews7895',
    followers_url: 'https://api.github.com/users/rews7895/followers',
    following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
    gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
    organizations_url: 'https://api.github.com/users/rews7895/orgs',
    repos_url: 'https://api.github.com/users/rews7895/repos',
    events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
    received_events_url: 'https://api.github.com/users/rews7895/received_events',
    type: 'User',
    site_admin: false,
    name: 'Junseok',
    company: 'compuzone',
    blog: '',
    location: 'Incheon',
    email: null,
    hireable: null,
    bio: 'Hello World',
    twitter_username: null,
    public_repos: 10,
    public_gists: 0,
    followers: 0,
    following: 2,
    created_at: '2018-03-05T03:23:36Z',
    updated_at: '2021-02-03T13:11:23Z'
  }
let repos = [
    {
      id: 334927557,
      node_id: 'MDEwOlJlcG9zaXRvcnkzMzQ5Mjc1NTc=',
      name: 'Next.js-starting-with-clone-coding',
      full_name: 'rews7895/Next.js-starting-with-clone-coding',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/Next.js-starting-with-clone-coding',
      description: '클론 코딩으로 시작하는 Next.js',
      fork: false,
      url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding',
      forks_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/forks',
      keys_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/events',
      assignees_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/merges',
      archive_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/Next.js-starting-with-clone-coding/deployments',
      created_at: '2021-02-01T11:28:29Z',
      updated_at: '2021-02-08T14:44:17Z',
      pushed_at: '2021-02-08T14:44:14Z',
      git_url: 'git://github.com/rews7895/Next.js-starting-with-clone-coding.git',
      ssh_url: 'git@github.com:rews7895/Next.js-starting-with-clone-coding.git',
      clone_url: 'https://github.com/rews7895/Next.js-starting-with-clone-coding.git',
      svn_url: 'https://github.com/rews7895/Next.js-starting-with-clone-coding',
      homepage: null,
      size: 703,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 334945637,
      node_id: 'MDEwOlJlcG9zaXRvcnkzMzQ5NDU2Mzc=',
      name: 'next.js',
      full_name: 'rews7895/next.js',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/next.js',
      description: '클론 코딩으로 시작하는 Next.js',
      fork: true,
      url: 'https://api.github.com/repos/rews7895/next.js',
      forks_url: 'https://api.github.com/repos/rews7895/next.js/forks',
      keys_url: 'https://api.github.com/repos/rews7895/next.js/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/next.js/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/next.js/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/next.js/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/next.js/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/next.js/events',
      assignees_url: 'https://api.github.com/repos/rews7895/next.js/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/next.js/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/next.js/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/next.js/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/next.js/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/next.js/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/next.js/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/next.js/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/next.js/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/next.js/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/next.js/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/next.js/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/next.js/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/next.js/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/next.js/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/next.js/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/next.js/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/next.js/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/next.js/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/next.js/merges',
      archive_url: 'https://api.github.com/repos/rews7895/next.js/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/next.js/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/next.js/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/next.js/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/next.js/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/next.js/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/next.js/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/next.js/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/next.js/deployments',
      created_at: '2021-02-01T12:39:38Z',
      updated_at: '2021-02-01T12:39:40Z',
      pushed_at: '2021-01-25T00:41:47Z',
      git_url: 'git://github.com/rews7895/next.js.git',
      ssh_url: 'git@github.com:rews7895/next.js.git',
      clone_url: 'https://github.com/rews7895/next.js.git',
      svn_url: 'https://github.com/rews7895/next.js',
      homepage: '',
      size: 4004,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main'
    },
    {
      id: 319217407,
      node_id: 'MDEwOlJlcG9zaXRvcnkzMTkyMTc0MDc=',
      name: 'Learn-next.js',
      full_name: 'rews7895/Learn-next.js',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/Learn-next.js',
      description: 'next.js 튜토리얼 진행',
      fork: false,
      url: 'https://api.github.com/repos/rews7895/Learn-next.js',
      forks_url: 'https://api.github.com/repos/rews7895/Learn-next.js/forks',
      keys_url: 'https://api.github.com/repos/rews7895/Learn-next.js/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/Learn-next.js/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/Learn-next.js/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/Learn-next.js/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/Learn-next.js/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/Learn-next.js/events',
      assignees_url: 'https://api.github.com/repos/rews7895/Learn-next.js/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/Learn-next.js/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/Learn-next.js/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/Learn-next.js/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/Learn-next.js/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/Learn-next.js/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/Learn-next.js/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/Learn-next.js/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/Learn-next.js/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/Learn-next.js/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/Learn-next.js/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/Learn-next.js/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/Learn-next.js/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/Learn-next.js/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/Learn-next.js/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/Learn-next.js/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/Learn-next.js/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/Learn-next.js/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/Learn-next.js/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/Learn-next.js/merges',
      archive_url: 'https://api.github.com/repos/rews7895/Learn-next.js/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/Learn-next.js/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/Learn-next.js/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/Learn-next.js/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/Learn-next.js/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/Learn-next.js/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/Learn-next.js/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/Learn-next.js/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/Learn-next.js/deployments',
      created_at: '2020-12-07T05:50:41Z',
      updated_at: '2020-12-08T14:27:24Z',
      pushed_at: '2020-12-08T14:27:21Z',
      git_url: 'git://github.com/rews7895/Learn-next.js.git',
      ssh_url: 'git@github.com:rews7895/Learn-next.js.git',
      clone_url: 'https://github.com/rews7895/Learn-next.js.git',
      svn_url: 'https://github.com/rews7895/Learn-next.js',
      homepage: null,
      size: 235,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 314802537,
      node_id: 'MDEwOlJlcG9zaXRvcnkzMTQ4MDI1Mzc=',
      name: 'django-study',
      full_name: 'rews7895/django-study',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/django-study',
      description: '장고 스터디 게시판 만들기',
      fork: false,
      url: 'https://api.github.com/repos/rews7895/django-study',
      forks_url: 'https://api.github.com/repos/rews7895/django-study/forks',
      keys_url: 'https://api.github.com/repos/rews7895/django-study/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/django-study/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/django-study/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/django-study/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/django-study/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/django-study/events',
      assignees_url: 'https://api.github.com/repos/rews7895/django-study/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/django-study/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/django-study/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/django-study/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/django-study/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/django-study/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/django-study/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/django-study/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/django-study/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/django-study/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/django-study/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/django-study/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/django-study/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/django-study/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/django-study/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/django-study/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/django-study/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/django-study/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/django-study/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/django-study/merges',
      archive_url: 'https://api.github.com/repos/rews7895/django-study/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/django-study/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/django-study/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/django-study/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/django-study/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/django-study/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/django-study/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/django-study/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/django-study/deployments',
      created_at: '2020-11-21T12:04:52Z',
      updated_at: '2020-11-22T14:55:28Z',
      pushed_at: '2020-11-22T14:55:26Z',
      git_url: 'git://github.com/rews7895/django-study.git',
      ssh_url: 'git@github.com:rews7895/django-study.git',
      clone_url: 'https://github.com/rews7895/django-study.git',
      svn_url: 'https://github.com/rews7895/django-study',
      homepage: null,
      size: 14,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Python',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 313009637,
      node_id: 'MDEwOlJlcG9zaXRvcnkzMTMwMDk2Mzc=',
      name: 'Django-practice',
      full_name: 'rews7895/Django-practice',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/Django-practice',
      description: '파이썬 웹 프로그래밍 연습',
      fork: false,
      url: 'https://api.github.com/repos/rews7895/Django-practice',
      forks_url: 'https://api.github.com/repos/rews7895/Django-practice/forks',
      keys_url: 'https://api.github.com/repos/rews7895/Django-practice/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/Django-practice/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/Django-practice/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/Django-practice/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/Django-practice/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/Django-practice/events',
      assignees_url: 'https://api.github.com/repos/rews7895/Django-practice/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/Django-practice/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/Django-practice/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/Django-practice/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/Django-practice/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/Django-practice/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/Django-practice/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/Django-practice/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/Django-practice/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/Django-practice/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/Django-practice/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/Django-practice/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/Django-practice/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/Django-practice/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/Django-practice/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/Django-practice/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/Django-practice/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/Django-practice/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/Django-practice/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/Django-practice/merges',
      archive_url: 'https://api.github.com/repos/rews7895/Django-practice/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/Django-practice/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/Django-practice/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/Django-practice/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/Django-practice/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/Django-practice/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/Django-practice/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/Django-practice/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/Django-practice/deployments',
      created_at: '2020-11-15T10:48:56Z',
      updated_at: '2020-11-18T14:06:20Z',
      pushed_at: '2020-11-18T14:06:43Z',
      git_url: 'git://github.com/rews7895/Django-practice.git',
      ssh_url: 'git@github.com:rews7895/Django-practice.git',
      clone_url: 'https://github.com/rews7895/Django-practice.git',
      svn_url: 'https://github.com/rews7895/Django-practice',
      homepage: null,
      size: 18,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Python',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 295667098,
      node_id: 'MDEwOlJlcG9zaXRvcnkyOTU2NjcwOTg=',
      name: 'Jump-to-Python',
      full_name: 'rews7895/Jump-to-Python',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/Jump-to-Python',
      description: '점프 투 파이썬 공부',
      fork: false,
      url: 'https://api.github.com/repos/rews7895/Jump-to-Python',
      forks_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/forks',
      keys_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/events',
      assignees_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/merges',
      archive_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/Jump-to-Python/deployments',
      created_at: '2020-09-15T08:42:46Z',
      updated_at: '2020-09-23T09:30:42Z',
      pushed_at: '2020-09-23T09:30:40Z',
      git_url: 'git://github.com/rews7895/Jump-to-Python.git',
      ssh_url: 'git@github.com:rews7895/Jump-to-Python.git',
      clone_url: 'https://github.com/rews7895/Jump-to-Python.git',
      svn_url: 'https://github.com/rews7895/Jump-to-Python',
      homepage: null,
      size: 63,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Python',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 283266846,
      node_id: 'MDEwOlJlcG9zaXRvcnkyODMyNjY4NDY=',
      name: 'kurtcobain_react',
      full_name: 'rews7895/kurtcobain_react',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/kurtcobain_react',
      description: '리액트로 소셜로그인과 게시판 구현',
      fork: false,
      url: 'https://api.github.com/repos/rews7895/kurtcobain_react',
      forks_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/forks',
      keys_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/events',
      assignees_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/merges',
      archive_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/kurtcobain_react/deployments',
      created_at: '2020-07-28T16:23:15Z',
      updated_at: '2020-07-31T13:34:14Z',
      pushed_at: '2021-01-21T10:22:55Z',
      git_url: 'git://github.com/rews7895/kurtcobain_react.git',
      ssh_url: 'git@github.com:rews7895/kurtcobain_react.git',
      clone_url: 'https://github.com/rews7895/kurtcobain_react.git',
      svn_url: 'https://github.com/rews7895/kurtcobain_react',
      homepage: null,
      size: 1386,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 2,
      license: null,
      forks: 0,
      open_issues: 2,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 283266658,
      node_id: 'MDEwOlJlcG9zaXRvcnkyODMyNjY2NTg=',
      name: 'kurtcobain_springboot',
      full_name: 'rews7895/kurtcobain_springboot',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/kurtcobain_springboot',
      description: '스프링부트로 소셜로그인과 게시판 구현',
      fork: false,
      url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot',
      forks_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/forks',
      keys_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/events',
      assignees_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/merges',
      archive_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/kurtcobain_springboot/deployments',
      created_at: '2020-07-28T16:22:29Z',
      updated_at: '2020-07-31T13:30:13Z',
      pushed_at: '2020-07-31T13:30:10Z',
      git_url: 'git://github.com/rews7895/kurtcobain_springboot.git',
      ssh_url: 'git@github.com:rews7895/kurtcobain_springboot.git',
      clone_url: 'https://github.com/rews7895/kurtcobain_springboot.git',
      svn_url: 'https://github.com/rews7895/kurtcobain_springboot',
      homepage: null,
      size: 599,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 267302850,
      node_id: 'MDEwOlJlcG9zaXRvcnkyNjczMDI4NTA=',
      name: 'Runnig-SpringBoot',
      full_name: 'rews7895/Runnig-SpringBoot',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/Runnig-SpringBoot',
      description: '스프링부트 시작하기',
      fork: false,
      url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot',
      forks_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/forks',
      keys_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/events',
      assignees_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/merges',
      archive_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/Runnig-SpringBoot/deployments',
      created_at: '2020-05-27T11:37:22Z',
      updated_at: '2020-05-27T11:39:44Z',
      pushed_at: '2020-05-27T11:38:14Z',
      git_url: 'git://github.com/rews7895/Runnig-SpringBoot.git',
      ssh_url: 'git@github.com:rews7895/Runnig-SpringBoot.git',
      clone_url: 'https://github.com/rews7895/Runnig-SpringBoot.git',
      svn_url: 'https://github.com/rews7895/Runnig-SpringBoot',
      homepage: '',
      size: 70,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 245188536,
      node_id: 'MDEwOlJlcG9zaXRvcnkyNDUxODg1MzY=',
      name: 'freelec-springboot2-webservice',
      full_name: 'rews7895/freelec-springboot2-webservice',
      private: false,
      owner: {
        login: 'rews7895',
        id: 37057277,
        node_id: 'MDQ6VXNlcjM3MDU3Mjc3',
        avatar_url: 'https://avatars.githubusercontent.com/u/37057277?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rews7895',
        html_url: 'https://github.com/rews7895',
        followers_url: 'https://api.github.com/users/rews7895/followers',
        following_url: 'https://api.github.com/users/rews7895/following{/other_user}',
        gists_url: 'https://api.github.com/users/rews7895/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rews7895/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rews7895/subscriptions',
        organizations_url: 'https://api.github.com/users/rews7895/orgs',
        repos_url: 'https://api.github.com/users/rews7895/repos',
        events_url: 'https://api.github.com/users/rews7895/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rews7895/received_events',
        type: 'User',
        site_admin: false
      },
      html_url: 'https://github.com/rews7895/freelec-springboot2-webservice',
      description: '스프링 부트와 AWS로 혼자 구현하는 웹서비스',
      fork: false,
      url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice',
      forks_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/forks',
      keys_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/teams',
      hooks_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/hooks',
      issue_events_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/issues/events{/number}',
      events_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/events',
      assignees_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/assignees{/user}',
      branches_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/branches{/branch}',
      tags_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/tags',
      blobs_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/languages',
      stargazers_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/stargazers',
      contributors_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/contributors',
      subscribers_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/subscribers',
      subscription_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/subscription',
      commits_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/contents/{+path}',
      compare_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/merges',
      archive_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/downloads',
      issues_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/issues{/number}',
      pulls_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/labels{/name}',
      releases_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/releases{/id}',
      deployments_url: 'https://api.github.com/repos/rews7895/freelec-springboot2-webservice/deployments',
      created_at: '2020-03-05T14:44:23Z',
      updated_at: '2020-03-09T15:11:42Z',
      pushed_at: '2020-03-09T15:11:40Z',
      git_url: 'git://github.com/rews7895/freelec-springboot2-webservice.git',
      ssh_url: 'git@github.com:rews7895/freelec-springboot2-webservice.git',
      clone_url: 'https://github.com/rews7895/freelec-springboot2-webservice.git',
      svn_url: 'https://github.com/rews7895/freelec-springboot2-webservice',
      homepage: null,
      size: 575,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    }
  ]
// // getInitialProps: 서버 사이드 데이터 패치를 위해 사용되던 함수
// name.getInitialProps = async ({query}) => {
//     const {name} = query
//     try {
//         const res = await fetch(`https://api.github.com/users/${name}`)
//         if(res.status == 200) {
//             const user = await res.json()
//             return {props: {user}}
//         }
//         return {props: {user}}
//     } catch(e) {
//         console.log(e)
//         return {}
//     }
// }
// // getStaticProps : 빌드 시에 데이터를 불러와 결과를 json으로 저장하여 사용. -> 일관된 데이터를 보여주게 된다.
// export const getStaticProps = async ({params}) => {
//     try {
//         const res = await fetch(`https://api.github.com/users/${params.name}`)
//         const user = await res.json()
//         if(res.status === 200) {
//             const user = await res.json()
//             return {props: {user, time: new Date().toISOString()}}
//         }
//         return {props: {time: new Date().toISOString()}}
//     } catch(e) {
//         console.log(e)
//         return {props: {time: new Date().toISOString()}}
//     }
// }

// // getStaticPaths: 페이지의 경로가 외부 데이터에 의존할 때 사용된다.
// export async function getStaticPaths() {
//     return {
//         paths: [{params: {name: 'rews7895'}}],
//         // fallback이 false이면 이외의 경로는 404 error 페이지로 가게 된다.
//         fallback: true,
//     }
// }

export default name
